service: serverless-poc

frameworkVersion: "3"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      noStart: true
    migration:
      dir: offline/migrations

provider: 
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  region: ap-south-1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
          
functions: 
  - ${file(src/handler/functions/create.yml)}
  - ${file(src/handler/functions/list.yml)}
  - ${file(src/handler/functions/get.yml)}
  - ${file(src/handler/functions/update.yml)}
  - ${file(src/handler/functions/delete.yml)}


resources: ${file(src/handler/resources.yml)}

